kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-v1
  namespace: scada
  labels:
    app: frontend
    version: v1
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubesphere.io/creator: dev-demon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
        version: v1
      annotations:
        dapr.io/app-id: frontend
        dapr.io/app-port: '80'
        dapr.io/enable-api-logging: 'true'
        dapr.io/enabled: 'true'
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - name: container-86izld
          image: 'registry.cn-guangzhou.aliyuncs.com/nanwanwang/frontend:latest'
          ports:
            - name: tcp-80
              containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
