kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend2-v1
  namespace: scada
  labels:
    app: backend2
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend2
      version: v1
  template:
    metadata:
      labels:
        app: backend2
        version: v1
      annotations:
        dapr.io/app-id: backend2
        dapr.io/app-port: '80'
        dapr.io/enable-api-logging: 'true'
        dapr.io/enabled: 'true'
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - name: backend2
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$BACKEND_NAME:latest
          ports:
            - name: tcp-80
              containerPort: 80
              protocol: TCP
          env:
            - name: APP_NAME
              value: backend2
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
